### ISSUE TITLE
Suggestion: Abbreviation for !strengths

### ISSUE THREAD

**Issue by bustacell** [Sp0ngeb0b/NexgenATB#1]
https://github.com/Sp0ngeb0b/NexgenATB/blob/0deffd2eb5fea50ff78bf45c041db64a4475e11b/Classes/NexgenATB.uc#L1033

Consider adding a shortcut to `!strengths` (like `!s` or `!str` or whatever), since the word _strengths_ is kinda hard to type for noobs like me and it is quite prone to errors. 
Futheremore an abbreviated keyword could be typed faster which is useful if you quickly want to check the strengths in between.

**Comment by Sp0ngeb0b** [comment]
`!str` abbreviation implemented in in [v0.22](https://github.com/Sp0ngeb0b/NexgenATB/commit/8c4a5e71e214e8f30ef38f6a50add99003176852)
